name: supreme_being
description: A meditation application written in Google's Flutter SDK

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^0.3.2
  another_flushbar: ^1.10.26
  auto_size_text: ^3.0.0
  autocomplete_textfield_ns: ^2.0.0
  chewie: ^1.2.2
  circular_reveal_animation: ^2.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.23.0+1
  get: ^4.3.8
  google_fonts: ^2.1.0
  ionicons: ^0.1.2
  json_annotation: ^4.3.0
  logging: ^1.0.2
  modal_bottom_sheet: ^2.0.0
  shared_preferences: ^2.0.8
  validators: ^3.0.0
  video_player: ^2.2.7
  

  

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.15.1+1
  json_serializable: ^6.0.1
  source_gen: ^1.1.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/svgs/
    - assets/videos/


  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Thin.ttf
          weight: 300
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
          weight: 200
        - asset: assets/fonts/Raleway/Raleway-ExtraLight.ttf
          weight: 100

    - family: Khula
      fonts:
        - asset: assets/fonts/Khula/Khula-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Khula/Khula-Bold.ttf
          weight: 700
        - asset: assets/fonts/Khula/Khula-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Khula/Khula-Regular.ttf
        - asset: assets/fonts/Khula/Khula-Light.ttf
          weight: 200

    - family: Julius
      fonts:
        - asset: assets/fonts/Julius/JuliusSansOne-Regular.ttf